### ISSUE TITLE
Horiztonal scroll bar bug

### ISSUE THREAD

**Issue by chanmathew** [microcipcip/gridy#2]
Hello!

First of all thanks for putting this awesome grid together.

Trying to implement this in a project right now, but I noticed that the following lines in `_griddy--mixins.scss` are causing horizontal scrolling:

``` css
 [#{$prefix}*="#{$gridName}"] {
    box-sizing: border-box;
    display: flex;
    flex-flow: row wrap;
    **margin-left: (-$gutter/2);**
    **margin-right: (-$gutter/2);**
  }
```

Just wondering if disabling these will affect anything? It seems to solve the scroll issue.

**Comment by chanmathew** [comment]
Hmm actually just updated to your latest version, this seems to do the trick:

``` css
  [#{$prefix}~="#{$wrapName}"] {
    max-width: $wrapWidth;
    width: 100%;
    margin-left: auto;
    margin-right: auto;
    // padding-left: $gutter;
    // padding-right: $gutter;
  }
  [#{$prefix}*="#{$gridName}"] {
    box-sizing: border-box;
    display: flex;
    flex-flow: row wrap;
    // margin-left: (-$gutter/2);
    // margin-right: (-$gutter/2);
  }
```
